AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy a simple EC2 Instance
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-006a0174c6c25ac06"
      InstanceType: t2.micro
      KeyName: UbuntuServerKeyPair
      BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50